const canvas = document.getElementById('game'), ctx = canvas.getContext('2d');
const W=canvas.width,H=canvas.height, keys={}, player={x:250,y:H/2,r:17,vx:0,vy:0}, ball={x:W/2,y:H/2,r:10,vx:0,vy:0};
let opponents=[], home=0, away=0, time=120, playing=false, last=0, audioOn=true;
const scoreH=document.getElementById('homeScore'), scoreA=document.getElementById('awayScore'), clock=document.getElementById('clock');
function resetPositions(){ Object.assign(player,{x:250,y:H/2,vx:0,vy:0}); Object.assign(ball,{x:W/2,y:H/2,vx:0,vy:0}); opponents=[{x:680,y:170,r:17},{x:790,y:440,r:17},{x:920,y:280,r:17}]; }
resetPositions();
addEventListener('keydown',e=>{ keys[e.code]=true; if(e.code==='Space'){e.preventDefault();kick()} });addEventListener('keyup',e=>keys[e.code]=false);
function kick(){if(!playing)return; const d=Math.hypot(ball.x-player.x,ball.y-player.y);if(d<47){let dx=ball.x-player.x,dy=ball.y-player.y,n=Math.hypot(dx,dy)||1;ball.vx=dx/n*15+4;ball.vy=dy/n*15; beep(180,.07)}}
function beep(f,d){if(!audioOn)return;const a=new (window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;o.connect(g);g.connect(a.destination);g.gain.setValueAtTime(.05,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.start();o.stop(a.currentTime+d)}
function update(dt){if(!playing)return;time=Math.max(0,time-dt/1000);clock.textContent=`${String(Math.floor(time/60)).padStart(2,'0')}:${String(Math.floor(time%60)).padStart(2,'0')}`;if(!time){playing=false;document.getElementById('status').textContent='FULL TIME';return}let ax=(keys.KeyD?1:0)-(keys.KeyA?1:0),ay=(keys.KeyS?1:0)-(keys.KeyW?1:0),n=Math.hypot(ax,ay)||1;player.vx=ax/n*4.5;player.vy=ay/n*4.5;player.x=Math.max(30,Math.min(W-30,player.x+player.vx));player.y=Math.max(28,Math.min(H-28,player.y+player.vy));
opponents.forEach((o,i)=>{let dx=ball.x-o.x,dy=ball.y-o.y,d=Math.hypot(dx,dy)||1;o.x+=dx/d*(1.25+i*.08);o.y+=dy/d*(1.25+i*.08);if(d<28){ball.vx=dx/d*3;ball.vy=dy/d*3}});let pd=Math.hypot(ball.x-player.x,ball.y-player.y);if(pd<player.r+ball.r+8){ball.vx+=(ball.x-player.x)/(pd||1)*.75;ball.vy+=(ball.y-player.y)/(pd||1)*.75}ball.x+=ball.vx;ball.y+=ball.vy;ball.vx*=.984;ball.vy*=.984;if(ball.y<15||ball.y>H-15){ball.vy*=-.8;ball.y=Math.max(15,Math.min(H-15,ball.y))}if(ball.x<15||ball.x>W-15){if(ball.y>H/2-100&&ball.y<H/2+100){goal(ball.x>W/2?'home':'away')}else{ball.vx*=-.8;ball.x=Math.max(15,Math.min(W-15,ball.x))}}}
function goal(team){if(team==='home'){home++;scoreH.textContent=home}else{away++;scoreA.textContent=away}playing=false;document.getElementById('goalBanner').classList.remove('show');void document.body.offsetWidth;document.getElementById('goalBanner').classList.add('show');beep(440,.22);setTimeout(()=>{resetPositions();playing=true},1500)}
function line(x1,y1,x2,y2){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}
function drawPlayer(p,color,number){ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle='rgba(0,0,0,.18)';ctx.beginPath();ctx.ellipse(3,17,18,6,0,0,7);ctx.fill();ctx.fillStyle='#f5b58d';ctx.beginPath();ctx.arc(0,-12,9,0,7);ctx.fill();ctx.fillStyle=color;ctx.beginPath();ctx.arc(0,3,17,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 12px Space Grotesk';ctx.textAlign='center';ctx.fillText(number,0,7);ctx.restore()}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#168b57';ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(255,255,255,.045)';for(let i=0;i<11;i+=2)ctx.fillRect(i*100,0,100,H);ctx.strokeStyle='rgba(255,255,255,.9)';ctx.lineWidth=3;ctx.strokeRect(25,25,W-50,H-50);line(W/2,25,W/2,H-25);ctx.beginPath();ctx.arc(W/2,H/2,82,0,7);ctx.stroke();ctx.beginPath();ctx.arc(W/2,H/2,4,0,7);ctx.fillStyle='#fff';ctx.fill();ctx.strokeRect(25,H/2-130,120,260);ctx.strokeRect(W-145,H/2-130,120,260);ctx.strokeRect(25,H/2-65,48,130);ctx.strokeRect(W-73,H/2-65,48,130);ctx.strokeStyle='rgba(255,255,255,.55)';ctx.strokeRect(2,H/2-100,23,200);ctx.strokeRect(W-25,H/2-100,23,200);opponents.forEach((o,i)=>drawPlayer(o,'#ff4b51',i+4));drawPlayer(player,'#276cff',10);ctx.fillStyle='rgba(0,0,0,.25)';ctx.beginPath();ctx.ellipse(ball.x+2,ball.y+10,10,4,0,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,7);ctx.fill();ctx.fillStyle='#182333';ctx.beginPath();ctx.arc(ball.x,ball.y,3.5,0,7);ctx.fill();}
function loop(now){let dt=Math.min(now-last,30);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
document.getElementById('startButton').onclick=()=>{playing=true;document.getElementById('startOverlay').classList.add('hidden')};document.getElementById('restartButton').onclick=()=>{home=away=0;time=120;scoreH.textContent=scoreA.textContent='0';clock.textContent='02:00';resetPositions();playing=true;document.getElementById('status').textContent='FIRST HALF';document.getElementById('startOverlay').classList.add('hidden')};document.getElementById('soundButton').onclick=()=>{audioOn=!audioOn;document.getElementById('soundButton').style.opacity=audioOn?'1':'.35'};
